image:
  file: gitpod/Dockerfile
tasks:
  - name: Setup project
    init: |
      mix deps.get
      MIX_ENV=dev mix compile
      MIX_ENV=test mix compile
      docker compose pull
    command: |
      docker compose up --wait
      mix ecto.setup
      iex -S mix phx.server
vscode:
  extensions:
    - elixir-lsp.elixir-ls
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
ports:
  - port: 4000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
