image:
  file: gitpod/Dockerfile
tasks:
  - name: Setup project
    init: |
      sh gitpod/install-asdf-plugins.sh
      asdf install
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      MIX_ENV=dev mix compile
      MIX_ENV=test mix compile
      docker-compose pull
    command: |
      docker-compose up -d
      mix ecto.setup
vscode:
  extensions:
    - elixir-lsp.elixir-ls
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
