image:
  file: gitpod/Dockerfile
tasks:
  - name: Install asdf .tool-versions
    init: |
      asdf install
      gp sync-done asdf-ready
  - name: Start docker-compose
    init: |
      docker-compose pull
    command: |
      docker-compose up -d
  - name: Compile app
    init: |
      gp sync-await asdf-ready
      mix local.hex --force
      mix deps.get
      MIX_ENV=test mix compile
      MIX_ENV=prod mix compile
    command: |
      iex -S mix phx.server
vscode:
  extensions:
    - elixir-lsp.elixir-ls
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
